version: '3.8'

services:
  webapp:
    image: nginx:latest
    container_name: dnschrisrathana.com.web_app
    networks:
      - my_network
    ports:
      - "8080:80"
    volumes:
      - ./webapp:/usr/share/nginx/html/index.html

  db:
    image: mysql:8
    container_name: christathana.com-sql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: christathana.com_db
      MYSQL_USER: christathana.com-user
      MYSQL_PASSWORD: secret....
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    docknet:
"9b688acc4123029e73e2490608a4Tdd64edede958Trade373621b38790b21164"
